[package]
name = "measure"
version = "0.0.1"
edition = "2024"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [ "config-toml" ] }

[dependencies]
tauri = { version = "2.0.0", features = [ "config-toml", "protocol-asset" ] }
serde = { version = "1.0", features = ["derive"] }

log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1", features = ["full"] }
rumqttc = "0.24"
dotenvy = "0.15"
serde_json = "1"
tokio-util = { version = "0.7", features = ["rt"] }
once_cell = "1.21.4"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "postgres", "tls-native-tls", "chrono"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }

[[bin]]
name = "measure"
path = "src-tauri/main.rs"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
